#!/bin/sh
find . -name "*~" -delete -or -name "\#*\#" -delete
rm -f CMakeCache.txt
rm -f cmake_install.cmake
rm -f Makefile
rm -rf CMakeFiles
rm -f libjson++.*
rm -f install_manifest.txt
rm -f CTestTestfile.cmake
